name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install backend deps
        working-directory: ./backend
        run: npm install
      - name: Run backend tests
        working-directory: ./backend
        run: npm test
      - name: Install frontend deps
        working-directory: ./frontend
        run: npm install
      - name: Run frontend build
        working-directory: ./frontend
        run: npm run build
